apiVersion: v1
kind: Service
metadata:
  name: apache-php-service
  labels:
    app: apache-php
spec:
  type: LoadBalancer   # Cambiato da NodePort a LoadBalancer
  externalTrafficPolicy: Cluster # Load balancing
  selector:
    app: apache-php
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
