apiVersion: v1
kind: Service
metadata:
  name: apache-php-service
  labels:
    app: apache-php
spec:
  type: NodePort
  selector:
    app: apache-php
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30354  # Puoi specificare un NodePort esplicitamente, oppure Kubernetes sceglierà uno disponibile
